### ISSUE TITLE
No for Tanzania (Swahili)

### ISSUE THREAD

**Issue by saigrandhi** [isitchristmas/web#102]
No in Swahili : hapana

**Comment by konklone** [comment]
Up for submitting a pull request to https://github.com/isitchristmas/web/blob/master/public/js/christmas.js? Do you know if `hakuna` would also work?

**Comment by saigrandhi** [comment]
In this context, it is more appropriate to have the answer be `hapana`. I will go ahead and add a pull request. 

I don't want to make a new issue post, so I want to ask if I could add Zambia as well. 
Zambia has English as the official language, but Bemba and Nyanja are the most often used local languages. In Bemba, `no` is `aweh` and `yes` is `eya`. In Nyanja, `no` is `nothing` and `yes` is `iyayi`

**Comment by konklone** [comment]
Absolutely - PRs welcome for any country!

**Comment by konklone** [comment]
Fixed in #104.
