### ISSUE TITLE
Incorrect calculation of Christmas dates

### ISSUE THREAD

**Issue by piranha32** [isitchristmas/web#115]
In Poland Christmas is a two day holiday. On the second day (Dec 26th) https://isitchristmas.com/ incorrectly reports no Christmas.

**Comment by konklone** [comment]
You are totally right, and I know there are other countries where Dec 25th isn't the right day, or the only day. I think I just can't commit to country-specific logic, though -- it would affect too many things in unpredictable ways, including things like API and [IFTTT](https://ifttt.com/isitchristmas) integration. I'm sorry to be exclusive or unwelcoming to Polish visitors, especially given that we try to translate the answer into Polish for them, but this is what makes the most sense for the site, I think.
