### ISSUE TITLE
microsoft band tile

### ISSUE THREAD

**Issue by tparnell8** [isitchristmas/web#117]
I use a MSFT band 2 webtile to intergrate with your site...mind if I publish it to the band gallery?

**Comment by konklone** [comment]
@tparnell8 No, by all means, that would be great! Please make sure any links to https://isitchristmas.com use `https://`. You don't need to cite me by name or anything, just please avoid giving the impression that you are the creator of the website.

**Comment by tparnell8** [comment]
here is the json file which has the metadata about the tile. I made sure it didn't imply any sort of ownership

```

{
  "manifestVersion": 1,
  "name": "Is It Christmas Yet",
  "description": "Band tile to tell you if it is Christmas. Will also notify you if it is\nhttps://isitchristmas.com/",
  "version": 1,
  "versionString": "1",
  "author": "https://isitchristmas.com/",
  "organization": "",
  "contactEmail": "",
  "tileIcon": {
    "46": "icons/tileIcon.png"
  },
  "icons": {},
  "refreshIntervalMinutes": 30,
  "resources": [
    {
      "url": "https://isitchristmas.com/rss.xml",
      "style": "Simple",
      "content": {
        "_1_rsschanneldescription": "/rss/channel/description",
        "_1_rsschannelitem1description": "/rss/channel/item[1]/description",
        "_1_rsschannelitem1title": "/rss/channel/item[1]/title"
      }
    }
  ],
  "pages": [
    {
      "layout": "MSBand_ScrollingText",
      "condition": "true",
      "textBindings": [
        {
          "elementId": "1",
          "value": "{{_1_rsschanneldescription}}"
        },
        {
          "elementId": "2",
          "value": "{{_1_rsschannelitem1description}}"
        }
      ]
    }
  ],
  "notifications": [
    {
      "condition": "{{_1_rsschannelitem1title}} == \"YES\"",
      "title": "{{_1_rsschanneldescription}}",
      "body": "{{_1_rsschannelitem1title}}"
    }
  ]
}


```

**Comment by konklone** [comment]
Huge :+1:. This is really cool.

**Comment by tparnell8** [comment]
it looks like this...it also sends a notification to the band on the "big day" 

https://goo.gl/photos/YkN6wYB1ZY9Ax3t37

**Comment by konklone** [comment]
That's _fantastic_. When it's in the gallery, please let me know what link to use to share this with people.

**Comment by tparnell8** [comment]
@konklone https://developer.microsofthealth.com/Gallery/PublicDetail/ad43a043-cd84-4e0e-937b-258ea53f394d

**Comment by konklone** [comment]
This is [outstanding](https://twitter.com/konklone/status/739567881596370947). Thank you for doing this and letting me know, @tparnell8 =)

**Comment by tparnell8** [comment]
Thanks man...
