### ISSUE TITLE
Use the browser locale instead of geoip for localization

### ISSUE THREAD

**Issue by ntnmrndn** [isitchristmas/web#119]
I believe in the internet.

**Comment by konklone** [comment]
I'd rather not require users to opt-in before the site translates the
answer. The IP-based approach has been working very well so far, can be
done quickly server-side with no meaningful performance cost, and is
extremely cheap ($12 each year for updates).

**Comment by ntnmrndn** [comment]
What do you mean you don't want the users to opt-in ? 
The information should be embed inside the HTTP Header in the Accept-Language field.
Every browser support that. 
IP geoloc is not a good way to infer one's language. At best it should be used as a fallback if the Accept-language header is absent.
Some people live in countries where they don't speak the language, use proxys, TOR, ...

**Comment by konklone** [comment]
@ntnmrndn My apologies, I misunderstood your request - I thought you were requesting that I use the HTML5 geolocation API. I understand what you're saying now.

I'd be interested in seeing how the locale matches up to the geolocated IP. Maybe I'll try to measure that this year.

But I'm not actually trying to translate the words for anyone who speaks that language. I really am trying to identify the country the vistor is in, and show them the word that's appropriate for that country. Similarly, when I turn the visitor's mouse cursor into their flag, I want to do that based on the country they're in, not what locale their device is set to. The charm is, I think in part, showing up to the site and figuring out that it's behaving a bit differently based on your physical location.

**Comment by ntnmrndn** [comment]
You make a very valid point, displaying the text in the country's language is

**Comment by datashaman** [comment]
South Africa has 11 official languages.

**Comment by pratnala** [comment]
India has a bajillion languages and many don't know Hindi. Should use user locale :)
