### ISSUE TITLE
Site says it’s not christmas, while it’s still christmas

### ISSUE THREAD

**Issue by Aaargh20318** [isitchristmas/web#139]
When visiting the site today, december 26, it says that it’s not christmas in Dutch ‘NEE’.  However, in the Netherlands Christmas lasts 2 days. Today is “tweede kerstdag” (literal translation: second christmasday) while the 25th is ‘eerste kerstdag’ (literal translation: first christmasday).

**Comment by konklone** [comment]
I appreciate this, but I just can't build in per-country complexity to Christmas detection. While some Christmas variations are based in nationality, many are based on religion, which I'd have no way of detecting. I feel bad for being Western-centric, but overall, the simplest and safest approach is to stick with the Western definition, which is a choice people will at least understand, even if it doesn't address their particular circumstance.

**Comment by BitScout** [comment]
Makeing a per-country array would not cover every convievable distinction, but it would be much better.
Example: Germany starts on the evening of the 24th and lasts until 26th.
