### ISSUE TITLE
help() on FF doesn't print help

### ISSUE THREAD

**Issue by openbrian** [isitchristmas/web#146]
Instead it opens a new tab with https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Helpers

**Comment by taylorsilva** [comment]
This doesn't appear to be an issue anymore 😄

**Comment by openbrian** [comment]
help() was apparently deprecated in Gecko 62 (https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Helpers#help)  Thanks @taylorsilva
