### ISSUE TITLE
Hindi

### ISSUE THREAD

**Issue by JonRider** [isitchristmas/web#150]
Hi love the site. Hindi (for India) should be written in Devanagari Script (Unicode).

**Yes** - हाँ

**No** - नहीं

**Comment by konklone** [comment]
Thanks @JonRider! I'll try and get this fixed for this Christmas. If you'd like to make a pull request, that will speed things up.

**Comment by JonRider** [comment]
Great I changed it to a pull request. Ill close this issue.
