### ISSUE TITLE
Consider switching to the XKCD algorithm

### ISSUE THREAD

**Issue by StopIteration** [isitchristmas/web#160]
The [XKCD Christmas algorithm](https://xkcd.com/2236/) is an improvement both in terms of efficiency and cache coherency and comes only at a small price in occasional inaccuracy.  The improved efficiency also helps to reduce carbon emissions, which threaten Santa Claus' polar residence.

**Comment by konklone** [comment]
It is an extremely minor accuracy hit, so I'll certainly consider it! Thank you for your product management advice and environmental analysis!

**Comment by RandomGuyDTB** [comment]
I really support this idea. If it was changed to the xkcd algorithm the JS could be tossed out and a static webpage could be served, a couple kilobytes at most. Compatibility with more browsers could also be achieved; plain HTML loads up on even Netscape fine.
